version: "3.3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./www:/usr/share/nginx/html
    ports:
      - 80:80
